openapi: 3.0.2
info:
    $ref: './info.yml'
tags:
    $ref: './tags.yml'
paths:
    $ref: './routes.yml'
externalDocs:
    description: 'NEM Developers'
    url: 'https://nemproject.github.io/'
servers:
    - url: 'http://localhost:7890'
      description: 'Local development'
    - url: 'http://hugetestalice2.nem.ninja:7890'
      description: 'Huge Alice Testnet'
    - url: 'http://hugealice2.nem.ninja:7890'
      description: 'Huge Alice Mainnet'
components:
    parameters:
        $ref: './parameters/_index.yml'
    requestBodies:
        $ref: './request_bodies/_index.yml'
    schemas:
        $ref: './schemas/_index.yml'
    responses:
        $ref: './responses/_index.yml'
